#!/usr/bin/env bash
# Deploys Escrow + TokenA + TokenB to a running Anvil, whitelists and mints, then writes the
# addresses into web/lib/addresses.ts and deployment-info.txt. Assumes Anvil on :8545.
set -euo pipefail
export PATH="$HOME/.foundry/bin:$PATH"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RPC="http://localhost:8545"
# Anvil account #0 (public dev key — local only)
PK="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

command -v forge >/dev/null || { echo "✖ Foundry no instalado"; exit 1; }
cast block-number --rpc-url "$RPC" >/dev/null 2>&1 || { echo "✖ Anvil no responde en $RPC. Arráncalo con: anvil"; exit 1; }

# Install libs if missing (they are gitignored).
[ -d "$ROOT/sc/lib/forge-std" ] || forge install foundry-rs/forge-std --no-git --root "$ROOT/sc" >/dev/null 2>&1 || true
[ -d "$ROOT/sc/lib/openzeppelin-contracts" ] || forge install OpenZeppelin/openzeppelin-contracts --no-git --root "$ROOT/sc" >/dev/null 2>&1 || true

echo "▶ Desplegando Escrow + TokenA + TokenB…"
OUT=$(cd "$ROOT/sc" && forge script script/Deploy.s.sol --rpc-url "$RPC" --broadcast --private-key "$PK" 2>&1) \
  || { printf '%s\n' "$OUT" | tail -8; echo "✖ Deploy falló"; exit 1; }

ESCROW=$(awk -F= '/ESCROW=/{print $2; exit}'  <<< "$OUT")
TOKEN_A=$(awk -F= '/TOKEN_A=/{print $2; exit}' <<< "$OUT")
TOKEN_B=$(awk -F= '/TOKEN_B=/{print $2; exit}' <<< "$OUT")
[ -n "$ESCROW" ] && [ -n "$TOKEN_A" ] && [ -n "$TOKEN_B" ] || { echo "✖ No se pudieron leer las direcciones"; exit 1; }

# --- write addresses for the frontend ---
mkdir -p "$ROOT/web/lib"
cat > "$ROOT/web/lib/addresses.ts" <<EOF
// Auto-generated by deploy.sh — do not edit by hand.
export const ESCROW_ADDRESS = "$ESCROW";
export const TOKEN_A_ADDRESS = "$TOKEN_A";
export const TOKEN_B_ADDRESS = "$TOKEN_B";
EOF

# --- deployment info ---
cat > "$ROOT/deployment-info.txt" <<EOF
Escrow DApp — deployment
RPC:      $RPC (chainId 31337)
Escrow:   $ESCROW
Token A:  $TOKEN_A (TKA)
Token B:  $TOKEN_B (TKB)

Minted 1000 TKA + 1000 TKB to:
  0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
  0x70997970C51812dc3A010C7d01b50e0d17dc79C8
  0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
EOF

echo ""
echo "✅ Desplegado"
echo "   Escrow  = $ESCROW"
echo "   Token A = $TOKEN_A"
echo "   Token B = $TOKEN_B"
echo "   → web/lib/addresses.ts y deployment-info.txt actualizados"
echo ""
echo "   Ahora: cd web && npm install && npm run dev"
