import deployment from "./deployment.json";
import type { Address } from "viem";

/**
 * Direcciones desplegadas, generadas por `script/DeployWeb.s.sol` (vm.writeJson).
 * Regenerar corriendo el script contra anvil. / Deployed addresses generated by DeployWeb.
 */
export interface Deployment {
  chainId: number;
  deployer: Address;
  identityCloneFactory: Address;
  identityRegistry: Address;
  tokenCloneFactory: Address;
  compliancePresetManager: Address;
  demoToken: Address;
}

export const addresses = deployment as Deployment;

/** Topic KYC obligatorio (debe coincidir con los scripts de deploy). */
export const KYC_TOPIC = 1n;

/** Preset de compliance (coincide con el enum on-chain CompliancePresetManager.Preset). */
export const PRESET = {
  NONE: 0,
  BASIC: 1,
  STANDARD: 2,
  STRICT: 3,
} as const;
export type PresetKey = keyof typeof PRESET;
